# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Client payload
      run: 'echo "${{ github.event.client_payload.build }}"'
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
    - name: Set up JDK 1.6
      uses: actions/setup-java@v1
      with:
        java-version: 1.6
    - name: Run tests with executable jar
      run: java -jar target/executable-tests.jar
